# Generated by Django 4.1.7 on 2023-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_type',
            field=models.CharField(choices=[('BTC', 'BTC'), ('DOGE', 'DOGE'), ('ETHEREUM', 'ETHEREUM')], default='BTC', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_amount',
            field=models.FloatField(default=10),
        ),
    ]
