# Generated by Django 4.1.7 on 2023-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_user_currency_type_alter_user_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
